### ISSUE TITLE
Version number from date?

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/send2cgeo#25]
Would it make sense to have a small gradle build script, that puts the current as version number? Similar to our app versioning scheme? That way we can "assemble" the script the same way we assemble all other components, and the version number surely is adapted without us forgetting it.

**Comment by Lineflyer** [comment]
Well I do use the pure Github UI to do smaller changes and fixes. Guess this won't work with any script?!
But nontheless we could just use the release date instead of a version number. Its only important that `new version > old version` in order for Greasemonkey/Tampermonkey to detect a newer version and trigger the automatic update.

**Comment by capoaira** [comment]
It would work with the date format YYYY.MM.DD. Maybe for the next version?

**Comment by Lineflyer** [comment]
Lets do it manual. I will prepare a PR for master for the next version. Version 202x.xx.xx should be always > 0.52

**Comment by Lineflyer** [comment]
I added a dummy date on `master`  and described the process for releasing in `readme.MD`
