### ISSUE TITLE
Web interface for cache import

### ISSUE THREAD

**Issue by schafma** [cgeo/send2cgeo#50]
It would be great if there would be a web interface where you could enter manually a list of GC-codes (separated by comma or one code per line) that will be sent via send2cgeo to the c:geo app.
This way it would be easy to import external lists (e.g. created with the "Map Compare" tool of project-gc) into c:geo.

Thx,
Marcus

**Comment by FriedrichFroebel** [comment]
There are already some similar issues like https://github.com/cgeo/send2cgeo/issues/14. As long as you have the right cookies and/or found the right API endpoints, a simple script should be able to do the job (I remember that I wrote a Python script for a similar use case some time ago).

**Comment by mirabilos** [comment]
For future reference, I managed to do it, thanks to the hints from the posters above (thanks!), by opening Firebug (F11) on GC.COM and copy/pasting a line like the following into the `Konsole` tab of Firebug:

    jQuery.each(["GC4HNPP","GC5QK6Y", …, "OC1424A","OC14357","OC1438D"], function (k,v) { jQuery.getScript("https://send2.cgeo.org/add.html?cache=" + v); })

(I’ve shortened the line, just list all the caches you want there.)

Then, I ignored all console warnings. A proper webinterface would be more welcome, though, of course.

**Comment by capoaira** [comment]
Hello,
Since sending a GC code list has been requested many times, I implemented this feature today.

You can test the function here: https://github.com/capoaira/send2cgeo/raw/send-multiple-caches/send2cgeo.user.js

Here it goes back to the current version: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js

How to use the function:
Click the "Send List" link. You can find this link on geocaching.com in the new and old dashboards under the renewal date and on opencaching.de at the top of your profile (https://www.opencaching.de/myhome.php).
Then a popup will open where you can insert your list and send it.
The seperator is irrelevant, it can be spaces, commas, line breaks, etc.
