### ISSUE TITLE
send2cgeo on old map stops opening the cache details

### ISSUE THREAD

**Issue by bekuno** [cgeo/send2cgeo#66]
When the script is active then the click on a cache icon has no result.
Without the script it shows the cache info.

**Comment by capoaira** [comment]
This seems to be due to the jquery version that was included. But I don't know how to avoid that.

**Comment by capoaira** [comment]
My PR #75 doesn't work. 
Maybe we have to do all onclick functions with .addEventListener () or .bind () so that this works with my solution.
But that is a lot of work. Does someone have a better idea? If not, I can do that, but not before the week after next week.

**Comment by capoaira** [comment]
A little to-do list just for me:

- [x] Make a function to add the c2cg-button
- [ ] remove `window.[functionname]() = function(){}` functions because they don't work, if the script not be insert into the Webpage. (not all have been removed now)
- [x] remove `// grand none`
**Bugs:**
- [ ] Browsemap: By opening a popup, if already one is open, the button is not shown
- [ ] New search: The button is insert 2 times
**Issues, that have to be fixed to check that everythink works fine**
- [ ] #77 recentlyviewed and nearest list shows no s2cg-button
- [x] #68 add a mutation observer to insert the button and show it in every language
**Change the s2cg call because the changes:**
- [x] Browsemap
- [x] Searchmap
- [x] New Search
- [ ] recentlyviewed and nearest list

These are notes for me so that I can keep an overview of what needs to be done.

**Comment by capoaira** [comment]
Hello,
I think I have found a solution. Please check if it's also fixes your problems.
Here the test script: https://github.com/capoaira/send2cgeo/raw/jQueryTest/send2cgeo.user.js

To get automatic updates again, please install the current release after you finish the test: https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js
